### ISSUE TITLE
Bug with roString vs String

### ISSUE THREAD

**Issue by RowanG1Bilue** [Roberto14/CompareAA#1]
This change is needed for me:

```
 typeaa1 = type(aa1[prop])
 typeaa2 = type(aa2[prop])
 if typeaa1 = "roString" then typeaa1 = "String"
 if typeaa2 = "roString" then typeaa2 = "String"
```

**Comment by Roberto14** [comment]
Hello,

Would you mind opening a PR with the fix?
Note there isn't a test suite for this code, so please try yourself as many cases you can :) 

Thanks,

**Comment by Roberto14** [comment]
https://github.com/Roberto14/CompareAA/pull/2
